#!/usr/bin/env ruby

# == Synopsis
#
# calc_rwalk_probs: Analyze graph reachability properties
#
# == Usage
#
# -h, --help:
#    Show this help.
#
# -o filename, --output filename
#
# -i filename, --input filename
#
# -m, --metropolis-hastings
#    Perform analysis of the metropolis hastings data.  Note that the following
#    fields are expected in the graph file for all nodes and edges:
#      nodes: mh_self_prob - the metropolis-hastings self-transition prob
#      edges: mh_trans_prob - the metropolis-hastings edge transition
#    Only works with the eigen solver currently, although there is no reason it
#    couldn't be extended (although that would be quite slow).
#
# -e, --ergodic
#    Use matrix multiplication on the ergodic input graph.  Much slower than
#    using the eigen solver, but give a precise mixing time to a given degree.
#
# -s, --eigen
#    Find the eigen vector of the first eigen value (1) and then take the
#    single-value decomposition.  This is an alternative method of finding the
#    static distribution.
#
# -r length, --random-walk length 
#    Length is an optional argument, default is 40.  This is an *extremely* slow
#    solver, meant no more than as a check for the eigen and ergodic solvers.
#    Don't use unless you want to wait for near eternity.

require 'rdoc/usage'
require 'getoptlong'

require 'rubygems'
require 'gsl'

require 'spinneret'

require 'stream_types'

#require 'profile'

$verbose = false

class PathTransitionMatrix
  def initialize(stream)
    @graph = RGL::DirectedAdjacencyGraph.new().read_from_dot(stream)
    @matrix = new_matrix()

    @cur_name = 0
    @vertex_names = {}
    @args = {}
  end

  def set_args(hash)
    @args.merge!(hash)
  end

  def new_matrix()
    return GSL::Matrix.alloc(@graph.num_vertices, @graph.num_vertices)
  end

  private

  def get_name(v)
    if !@vertex_names.has_key? v
      @vertex_names[v] = @cur_name  
      @cur_name += 1
    end

    return @vertex_names[v]
  end

end

class GraphRandomWalk < PathTransitionMatrix
  DEFAULT_WALK_LENGTH = 40

  def initialize(stream, length = DEFAULT_WALK_LENGTH)
    super(stream)
    @converged = false
    @vert_edges = {}
    @args[:length] = length  # possibly overwritten by a call to set_args()
  end

  def converge(type)
    verts = @graph.vertices

    puts "Using random walks of length #{@args[:length]}." if $verbose
    
    prev_probs = GSL::Matrix.alloc(@graph.num_vertices, @graph.num_vertices)
    i = 0
    while(!@converged)
      verts.each do | v |
        #puts "0x#{v.to_s[0..10]}..." if $verbose
        verts.size.times do
          u = v
          @args[:length].times { u = vertices(u).rand() }

          v_name, u_name = get_name(v), get_name(u)
          @matrix.set(v_name, u_name, @matrix.get(v_name, u_name) + 1)
        end
      end

      @probs = normalize(@matrix, (i + 1) * verts.size)
      @converged = @probs.equal?(prev_probs)

      if(i % 10 == 4)
        if $verbose
          puts "#{i+1} steps have passed (sqme #{(@probs - prev_probs).norm})"
        end
        f = File.new("#{i+1}.probs", "w")
        write_node_probs(f)
        f.close() # force flush in case of early exit
      end
      i += 1

      prev_probs = @probs
    end  # !converged

  end

  def write_node_probs(stream)
#    return unless @converged
  
    @vertex_names.each do | key, value |
      # Note, all rows should be created equal, but maybe we should average
      # here instead of just picking the first one
      col = @probs.col(value)
      stream.write("#{key} #{col[0]} #{col.sum / col.size}\n")
    end
  end

  private

  def vertices(v)
    if !@vert_edges.has_key?(v)
      @vert_edges[v] = @graph.adjacent_vertices(v)
    end

    return @vert_edges[v]
  end

  def normalize(matrix, trials)
    new_matrix = GSL::Matrix.alloc(@graph.num_vertices, @graph.num_vertices)

    matrix.size1.times do | i | 
      row = matrix.get_row(i)
      sum = row.sum
      row.collect! { | val | val / sum }
      new_matrix.set_row(i, row)
    end

    return new_matrix
  end

end

class ErgodicTransitionMatrix < PathTransitionMatrix

  def initialize(stream)
    super(stream)

    @mh_matrix = nil
    @converged = nil
  end

  def write_node_probs_dot(stream)
    return unless @converged

    @vertex_names.each do | key, value |
      # Note, all rows should be created equal, but maybe we should average
      # here instead of just picking the first one
      vec = GSL::Vector::alloc(@converged.col(value))
      @graph.add_vertex_property(key, :prob_rwalk_mean, Stats::mean(vec))
      @graph.add_vertex_property(key, :prob_rwalk_sd, Stats::sd(vec))
    end

    stream << @graph.to_dot()
  end

  def write_node_probs(stream)
    return unless @converged

    @vertex_names.each do | key, value |
      vec = GSL::Vector::alloc(@converged.col(value))
      stream.write("#{key} #{Stats::mean(vec)} #{Stats::sd(vec)}\n")
    end
  end

  def converge(type)
    generate_matrix()

    puts "Performing convergence..." if $verbose

    res = @matrix ^ 2
    @converged = res * @matrix

    i = 0
    while !res.equal?(@converged)
      res = @converged
      @converged = @converged * @matrix

      if(i % 10 == 9)
        if $verbose
          puts "#{i+1} steps have passed (sqme #{(@converged - res).norm})"
        end
      end
      i += 1
    end

    puts "#{i+1} steps have passed - converged" if $verbose
  end

  private

  def generate_matrix
    puts "Generating..." if $verbose
    @graph.each_vertex do | v |
      adj_v = @graph.adjacent_vertices(v)
      size = adj_v.length.to_f
      adj_v.each do | u |
        @matrix.set(get_name(v), get_name(u), 1.0 / size)
      end
    end

    puts "Checking..." if $verbose
    error = false
    @matrix.each_row { | row | error = true unless row.sum == 1.0 }
    if error
      $stderr.write("WARN: Possible precision problems. Usually not serious.\n")
    end

    # Check if there was a debug request - this format can be imported easily
    # into octave.
    if @args.has_key?(:print_transition_matrix)
      puts "# name: P"
      puts "# type: matrix"
      puts "# rows: #{@matrix.size1}"
      puts "# columns: #{@matrix.size2}"
      @matrix.each_row do | row |
        str = []
        row.each { | val | str << val.to_s }
        puts str.join(" ")
      end
    end
  end

  def generate_mh_matrix()
    puts "Generating mh..." if $verbose

    @mh_matrix = new_matrix()
    @graph.each_vertex do | v |
      adj_v = @graph.adjacent_vertices(v)
      size = adj_v.length.to_f

      self_prob = @graph.get_vertex_property(v, :mh_self_prob)
      next if(self_prob == 1.0)  # Don't include this node - this leave a row empty!  NEeds to be fixed!

      if self_prob.nil?
        puts "Node #{v} has a nill self prob"
      end
      @mh_matrix.set(get_name(v), get_name(v), self_prob)
      adj_v.each do | u |
        @mh_matrix.set(get_name(v), get_name(u), 
                       @graph.get_edge_property(v, u, :mh_trans_prob))
      end
    end

    puts "Checking..." if $verbose
    error = false
    @mh_matrix.each_row { | row | error = true unless row.sum == 1.0 }
    if error
      $stderr.write("WARN: Possible precision problems. Usually not serious.\n")
    end

  end
end

class ErgodicEigenSolver < ErgodicTransitionMatrix
  def initialize(stream)
    super(stream)
  end

  def write_node_probs_dot(stream)
    return unless @converged

    @vertex_names.each do | key, value |
      @graph.add_vertex_property(key, :prob_rwalk_mean, @final[value])
      # there is no sd, as we are not averaging across a set of values
      # in a "converged" matrix
      @graph.add_vertex_property(key, :prob_rwalk_sd, 0.0)

      # Check if we have MH data to report as well
      if(@mh_matrix) 
        @graph.add_vertex_property(key, :prob_rwalk_mh_mean, @final_mh[value])
      end
    end

    graph_params = {"mixing_time_bound" => @mix_time_l}
    graph_params["mixing_time_bound_mh"] = @mix_time_l_mh if @mh_matrix
    stream << @graph.to_dot(graph_params)
  end

  def write_node_probs(stream)
    return unless @converged

    @vertex_names.each do | key, value |
      stream << "#{key} #{@final[value]} #{0.0}\n"
    end
  end

  def converge(type)
    # generates the traditional src->dest matrix  but we take the 
    # transpose below in order to  get the dest<-src form needed for 
    # the right  eigenvector to make sense.
    case type
    when :mh
      generate_mh_matrix()
      p = @mh_matrix
    else
      generate_matrix()
      p = @matrix 
    end
  
    puts "Performing decomposition, solving for eigenvectors..." if $verbose

    eigval, eigvec = Eigen::nonsymmv(p.transpose)
    Eigen::nonsymmv_sort(eigval, eigvec, GSL::Eigen::SORT_ABS_DESC)

    # puts eigval[0]
  
    if eigval[0].imag != 0 
      if eigval[0].real.deltafrom(1.0, 0.0001)
        throw "No solution found using eigen solver"  
      end
    end

    sol = eigvec.col(0)
    arr = []
    sol.each do | val |
      if val.imag == 0
        arr << val.real
      else
        throw "eigenvector corresponding to eigenvalue 1 has imaginary components!"
      end
    end
    sol = GSL::Vector::alloc(arr)

    if type == :mh
      @final_mh = sol / sol.sum
      @mix_time_l_mh = Math::log(@vertex_names.length) / 1.0 - mod(eigval[1])
    else
      @final = sol / sol.sum
      @mix_time_l = Math::log(@vertex_names.length) / 1.0 - mod(eigval[1])
    end

    @converged = true
  end

  private

  def mod(complex)
    return Math.sqrt(complex.real**2 + complex.imag**2)
  end
end

def puts(str)
  $stderr.puts str
end

opts = GetoptLong.new(
        ['--help',                   '-h', GetoptLong::NO_ARGUMENT],
        ['--output',                 '-o', GetoptLong::REQUIRED_ARGUMENT],
        ['--input',                  '-i', GetoptLong::REQUIRED_ARGUMENT],
        ['--metropolis-hastings',    '-m', GetoptLong::NO_ARGUMENT],
        ['--ergodic',                '-e', GetoptLong::NO_ARGUMENT],
        ['--eigen',                  '-s', GetoptLong::NO_ARGUMENT],
        ['--initial-matrix',         '-t', GetoptLong::NO_ARGUMENT],
        ['--random-walk',            '-r', GetoptLong::OPTIONAL_ARGUMENT],
        ['--verbose',                '-v', GetoptLong::NO_ARGUMENT])

output = $stdout
input = $stdin
convergence_class = nil
#eigen_converge = false
do_mh = false
args = {}
opts.each do | opt, arg |
  case opt
  when '--help'
    RDoc::usage
    exit(0)
  when '--output'
    output = get_output_stream(arg)
  when '--metropolis-hastings'
    do_mh = true
  when '--input'
    input = get_input_stream(arg)
  when '--ergodic'
    convergence_class = ErgodicTransitionMatrix
  when '--random-walk'
    convergence_class = GraphRandomWalk
    args[:length] = arg.to_i unless arg.nil?
  when '--eigen'
    convergence_class = ErgodicEigenSolver
  when '--initial-matrix'
    args[:print_transition_matrix] = true
  when '--verbose'
    $verbose = true
  end
end

if(output.nil? || input.nil? || convergence_class.nil?)
  RDoc::usage
  exit(-1)
end

p = convergence_class.new(input)
p.set_args(args)
puts "Running convergence..." if $verbose
p.converge(:normal)
p.converge(:mh)                 if(do_mh)
p.write_node_probs_dot(output)
output.close()      # Have to explicitly close gzip streams
puts "Done." if $verbose
