#!/usr/bin/env ruby

# == Synopsis
#
# calc_lowhigh
#
# == Usage
#
# -h, --help:
#    Show this help.
#
# -o filename, --output filename
#    Defaults to stdout
#
# -i filename, --input filename
#    Defaults to stdin
#
# -r row, --row row
#    Which row of data to find the normal of
#
# -s character, --separator character
#    Which character to use as a separator.  Defaults to whitespace.
#

require 'rdoc/usage'
require 'getoptlong'
require 'zlib'

require 'rubygems'
require 'gsl'

require 'spinneret'

require 'stream_types'

opts = GetoptLong.new(
        ['--help',                   '-h', GetoptLong::NO_ARGUMENT],
        ['--output',                 '-o', GetoptLong::REQUIRED_ARGUMENT],
        ['--input',                  '-i', GetoptLong::REQUIRED_ARGUMENT],
        ['--row',                    '-r', GetoptLong::REQUIRED_ARGUMENT],
        ['--separator',              '-s', GetoptLong::REQUIRED_ARGUMENT])

output = $stdout
input = $stdin
row = -1
sep = /\s+/
opts.each do | opt, arg |
  case opt
  when '--help'
    RDoc::usage
    exit(0)
  when '--output'
    output = get_output_stream(arg)
  when '--input'
    input = get_input_stream(arg)
  when '--row'
    row = arg.to_i
  when '--separator'
    sep = arg
  end
end

if(output.nil? || input.nil? || row == -1)
  RDoc::usage
  exit(-1)
end

vals = []
input.each_line { | line | vals << line.split(sep)[row].to_f }
v = GSL::Vector::alloc(vals)
output.write("#{v.min} #{v.max}\n")
output.close()
