#!/usr/bin/env ruby

# == Synopsis
#
# extract_vertex_props
#
# Reads a given dot topology and returns tuples of attributes from each vertex,
# with one vertex per line, each value separated by whitespace.  Attributed
# with whitespace need to be stored in the dot file escaped.
#
# == Usage
#
# -h, --help:
#    Show this help.
#
# -o filename, --output filename
#    Defaults to stdout
#
# -i filename, --input filename
#    Defaults to stdin
#
# -d, --print-id
#    Forces the id of the node to be printed first.
#
# -p property:property:...:property, --vertex-properties ...
#    Extract the given properties.  The ':' character is in no way supported.
#

require 'rdoc/usage'
require 'getoptlong'
require 'zlib'

require 'rubygems'
require 'gsl'

require 'spinneret'

require 'stream_types'

opts = GetoptLong.new(
        ['--help',                   '-h', GetoptLong::NO_ARGUMENT],
        ['--output',                 '-o', GetoptLong::REQUIRED_ARGUMENT],
        ['--input',                  '-i', GetoptLong::REQUIRED_ARGUMENT],
        ['--print-id',               '-d', GetoptLong::NO_ARGUMENT],
        ['--vertex-properties',      '-p', GetoptLong::REQUIRED_ARGUMENT])

output = $stdout
input = $stdin
props = nil
force_id = false
opts.each do | opt, arg |
  case opt
  when '--help'
    RDoc::usage
    exit(0)
  when '--output'
    output = get_output_stream(arg)
  when '--input'
    input = get_input_stream(arg)
  when '--print-id'
    force_id = true
  when '--vertex-properties'
    props = arg.split(':').map { | prop | prop.to_sym }
  end
end

if(output.nil? || input.nil? || props.nil?)
  RDoc::usage
  exit(-1)
end

graph = RGL::DirectedAdjacencyGraph.new().read_from_dot(input)

verts = graph.vertices.sort

verts.each do | v |
  vals = []
  props.each do | prop |
    vals << graph.get_vertex_property(v, prop)
  end

  output.write("#{v} ") if force_id
  output.write(
    vals.map do | val | 
      if val.class == Float
        sprintf("%9.9f", val);
      else
        val.to_s
      end
    end.join(" ") + "\n"
  );
end

output.close()
