#! /usr/bin/env ruby

# == Synopsis
#
# gen-substrate-wl: Generates a workload for spinneret tests
#
# == Usage
#
# gen-substrate-wl [OPTIONS]
#
# -h, --help
#    Show this help
#
# -o filename, --filename filename
#    Sets the output file
#
# -l num, --sim-max-length num
#    Sets the maximum length of the generated workload
#
# -a num, --address-space num
#    The address space of the workload
#
# -n num, --num-nodes num
#    Number of nodes in network
#
# -z, --all-joins-first
#    All nodes join the network first
#
# -j secs, --mean-join-time secs
#    Time between nodes joining the network, where 0 is instantanious.  0 is
#    the default.
#
# -x secs, --mean-failure-time secs
#    Time between failure for each node, where 0 is no failure.  0 is the 
#    default.
#
# -q secs, --mean-leave-time secs
#    Mean time before a node leaves the network, where 0 is never.  0 is the 
#    default.
#
# -r secs, --mean-rejoin-time secs
#    Mean time before a node rejoins the network after leaveing or a failure,
#    where 0 indicates nodes to not rejoin.  0 is the default.
#
# -s secs, --mean-search-time secs
#    Time between searching for each node, where 0 is no search.  0 is the 
#    default.
#
# -t types, --search-types types
#    Specifies the search types.  Each type is a pair, name:pct, where name
#    specifies the type and pct the percent of the time it occurs.  Multiple
#    types can be given if they are seperated with commas:
#        dht:0.2,kwalk:0.8
#    would create a workoad with 20% DHT searches, and 80% random k-walker
#    searches.  Note that the sum of the probabilities must be <= to 1.0.
#    Defaults to
#        dht:0.5,kwalk:0.5
#
# -f time:pct, --static-failure time:pct
#    Create a static failire in the network of pct percent nodes at time.  For
#    example:
#        -f 60000:0.5
#    would create a static failure of 50% of all nodes at time 60000 (60
#    seconds).  Defaults to 0:0.0

######
# The basic FSM for this generator is as follows:
#
#   join    ---------   leave    ------ 
# -------->| running |--------->| left |
#       --> ---------            ------ 
#      /    /    ^  \                ^
#     /    /      \  \failure        |
#     |    |      |   \    --------  | leave
#     |     \    /     \->| failed |-/
#     |      ----          -------- 
#     |     search             |
#     |                       /
#     \----------------------/
#             recover
#
######

# Builtins
require 'singleton'
require 'getoptlong'
require 'rdoc/usage'

require 'rubygems'
require 'gosim'

require 'spinneret/math_ext'

# Externals
require 'gsl'
require 'zlib'

DEFAULT_SEARCH_TYPE = "dht:0.5,kwalk:0.5"
DEFAULT_STATIC_FAILURE = "0:0.0"

# These methods can take a filename

class WLPrinter
  include Singleton

  def init(sim, file)
    @sim = sim
    @last_time = -1
    @file = file
  end

  def printf(fmt_str, *args)
    if(@sim.time > @last_time)
      @last_time = @sim.time
      @file.write("time #{@sim.time}\n")
    end

    @file.write(sprintf(fmt_str, *args))
  end

  def flush()
    @file.close()
  end
end

class Killer < GoSim::Entity
  def initialize(end_time)
    super()

    @sim.schedule_event(:die, @sid, end_time, nil)
  end

  def handle_die(e)
    WLPrinter.instance.flush()
    exit(0)
  end
end

class StaticFailureHandler < GoSim::Entity
  def initialize(time, pct)
    super()

    set_timeout(time) {
      nodes = NodeList::instance.nodes

      num_fail = (nodes.length * pct).to_i
      while(num_fail > 0)
        n = nodes.rand

        #if we aren't alive, then find one that is
        next if n.left == true

        #else kill the node
        @sim.schedule_event(:failure, n.sid, 0, false)
        num_fail -= 1
      end
    }
  end
end

class SearchType
  attr_reader :name, :prob

  def initialize(name, prob)
    @name, @prob = name, prob.to_f
  end
end

def parse_search_types(types_str)
  types = types_str.split(',').map { | t | SearchType.new(*t.split(':')) }
  tot_prob = 0.0
  types.each { | t | tot_prob += t.prob }
  if tot_prob > 1.0
    puts "Total search probability is more than 1.0.\n"
    exit(2)
  end

  return types
end

def choose_search_method(types)
  tot_prob = 0.0
  types.each { | type | tot_prob += type.prob }

  types.each do | type |  
    if rand() < type.prob / tot_prob
      return type
    end
    tot_prob -= type.prob
  end

  nil
end

opts = GetoptLong.new(
        ['--help',               '-h', GetoptLong::NO_ARGUMENT],
        ['--filename',           '-o', GetoptLong::REQUIRED_ARGUMENT],
        ['--sim-max-length',     '-l', GetoptLong::REQUIRED_ARGUMENT],
        ['--address-space',      '-a', GetoptLong::REQUIRED_ARGUMENT],
        ['--num-nodes',          '-n', GetoptLong::REQUIRED_ARGUMENT],
        ['--all-joins-first',    '-z', GetoptLong::NO_ARGUMENT],
        ['--mean-join-time',     '-j', GetoptLong::REQUIRED_ARGUMENT],
        ['--mean-failure-time',  '-x', GetoptLong::REQUIRED_ARGUMENT],
        ['--mean-leave-time',    '-q', GetoptLong::REQUIRED_ARGUMENT],
        ['--mean-rejoin-time',   '-r', GetoptLong::REQUIRED_ARGUMENT],
        ['--mean-search-time',   '-s', GetoptLong::REQUIRED_ARGUMENT],
        ['--search-types',       '-t', GetoptLong::REQUIRED_ARGUMENT],
        ['--static-failure',     '-f', GetoptLong::REQUIRED_ARGUMENT] )

Settings = Struct.new("Settings", :addr_space, :join_first, 
                                  :mjt, :mft, :mlt, :mrt, :mst, 
                                  :search_types, :static_failure)
class Settings
  def to_s
   "# Settings---\n# addr_space: #{addr_space}\n# join_first?: #{join_first}\n" +
   "# mjt: #{mjt}\n# mft: #{mft}\n# mft: #{mlt}\n# mrt: #{mrt}\n" + 
   "# mst: #{mst}\n# search_types: #{search_types}\n" +
   "# static_failure: #{static_failure}\n"
  end
end

settings = Settings.new(0, false, 0, 0, 0, 0, 0, 
                        DEFAULT_SEARCH_TYPE, DEFAULT_STATIC_FAILURE)

nodes = 0
filename = nil
length = 0
opts.each do | opt, arg |
  case opt
  when '--help'
    RDoc::usage
  when '--filename'
    filename = arg
  when '--sim-max-length'
    length = arg.to_i
  when '--address-space'
    settings.addr_space = arg.to_i
  when '--num-nodes'
    nodes = arg.to_i
  when '--all-joins-first'
    settings.join_first = true
  when '--mean-join-time'
    settings.mjt = arg.to_f
  when '--mean-failure-time'
    settings.mft = arg.to_f
  when '--mean-leave-time'
    settings.mlt = arg.to_f
  when '--mean-rejoin-time'
    settings.mrt = arg.to_f
  when '--mean-search-time'
    settings.mst = arg.to_f
  when '--search-types'
    settings.search_types = arg
  when '--static-failure'
    settings.static_failure = arg
  end
end

if(settings.addr_space == 0)
  p settings
  printf("Need to specify at least --address-space.\n")
  exit(0)
end

if(settings.join_first && nodes == 0)
  printf("Must specify --num-nodes when using the --all-joins-first option.\n")
  exit(0)
end

if(length == 0)
  printf("WARN: generating an infinite trace.\n")
#else
#  Killer.new(length)
end

if(settings.static_failure != DEFAULT_STATIC_FAILURE)
  time, pct = settings.static_failure.split(":")
  StaticFailureHandler.new(time.to_i, pct.to_f)
end

# Set the filename if one wasn't given
filename ||= File.join('workloads', "a#{settings.addr_space}-n#{nodes}-j#{settings.mjt}.wl")

file = Zlib::GzipWriter.open(filename)
#file = File.open(filename, "w")
file.write(settings)
file.write("# num_nodes: #{nodes}\n")
file.write("# sim_length: #{length}\n")

puts settings

settings.search_types = parse_search_types(settings.search_types)

WLPrinter.instance.init(GoSim::Simulation.instance, file)

GSL::Rng.env_setup
$R = GSL::Rng.alloc("mt19937")

class NodeList
  include Singleton

  attr_accessor :nodes

  def random_live_node
    n = nil
    while((n = @nodes.rand).left == true)
    end
    return n
  end
end

class NodeFactory < GoSim::Entity
  def initialize(num_nodes, settings)
    super()

    @num_nodes, @settings = num_nodes, settings
    @num_nodes = -1  if @num_nodes == 0   # Generating an inifinite number

    NodeList.instance.nodes = []
    @wl = WLPrinter.instance
    @node_ids = []

    @sim.schedule_event(:node_gen, @sid, 
                        $R.poisson(@settings.mjt).round, nil)
  end

  def handle_node_gen(e)
    nodes = NodeList.instance.nodes

    if nodes.length == @settings.addr_space
      printf("ERROR: Address space full.\n")
      exit(1)
    end

    while(@node_ids.include?(node_id = rand(@settings.addr_space)))  
    end
    @wl.printf("%d init %d\n", node_id, node_id)
    nodes << NodeObj.new(node_id, @settings)  if !@settings.join_first
    @node_ids << node_id

    @num_nodes -= 1
    if(@num_nodes != 0)
      @sim.schedule_event(:node_gen, @sid, 
                          $R.poisson(@settings.mjt).round, nil)
    elsif(@settings.join_first)
      spawn_nodes
    end
  end

  private

  def spawn_nodes
    nodes = NodeList.instance.nodes
    @node_ids.each { | n | nodes << NodeObj.new(n, @settings) }
  end
end

class NodeObj < GoSim::Entity
  attr_accessor :left, :id

  def initialize(id, settings)
    super()

    @id, @settings = id, settings
    @left = false
    
    @wl = WLPrinter.instance

    if @settings.mft != 0 
      @sim.schedule_event(:failure, @sid, 
                          $R.poisson(@settings.mft).round, nil)  
    end

    if @settings.mlt != 0
      @sim.schedule_event(:leave, @sid, 
                          $R.poisson(@settings.mlt).round, nil)  
    end

    if @settings.mst != 0    
      @sim.schedule_event(:send, @sid, 
                          $R.poisson(@settings.mst).round, nil)     
    end
  end

  def handle_send(e)
    type = choose_search_method(@settings.search_types)
    if(!@left && !type.nil?)
      @wl.printf("%d search_%s %d\n", @id, type.name, 
                 NodeList::instance.random_live_node.id)
    end
    @sim.schedule_event(:send, @sid, 
                        $R.poisson(@settings.mst).round, nil)
  end

  def handle_failure(e)
    return  if @left == true

    @wl.printf("%d failure\n", @id)
    @left = true
    if @settings.mrt != 0 && e.nil?
      @sim.schedule_event(:recover, @sid, 
                          $R.poisson(@settings.mrt).round, nil)
    end
  end

  def handle_leave(e)
    @wl.printf("%d leave\n", @id)
    @left = true
    NodeList.instance.nodes.delete(self)
  end
  
  def handle_recover(e)
    @wl.printf("%d recover\n", @id)
    @left = false
    @sim.schedule_event(:failure, @sid, 
                        $R.poisson(@settings.mft).round, nil)
  end
end

NodeFactory.new(nodes, settings)
if length != 0
  GoSim::Simulation.run(length)
else
  GoSim::Simulation.run()
end
WLPrinter.instance.flush()
